- name: Ensure python3-cryptography is installed
  become: true
  ansible.builtin.apt:
    name: python3-cryptography
    state: latest

- name: Ensure SSH key exists
  openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519
    size: 256
    mode: '0600'
    passphrase: "{{ ssh_key_passphrase }}"
  register: ssh_key

- name: Copy new generated pubkey to ansible control node 
  fetch:
    src: ~/.ssh/id_ed25519.pub
    dest: "../ssh_public_keys/{{ hostname }}_id_ed25519.pub"
    flat: yes
