- name: Ensure Flatpak is installed
  become: true
  apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present
    update_cache: yes

- name: Add Flatpak remotes
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system

- name: Install Flatpak applications
  become: true
  community.general.flatpak:
    name:
      - com.github.tchx84.Flatseal
      - com.visualstudio.code
      - com.discordapp.Discord
      - com.bitwarden.desktop
      - net.lutris.Lutris
      - com.usebottles.bottles
      - com.github.iwalton3.jellyfin-media-player
    state: present
    remote: flathub
