- name: Ensure Debian backports sources list is present
  become: true
  copy:
    src: debian-backports.sources
    dest: /etc/apt/sources.list.d/debian-backports.sources
    owner: root
    group: root
    mode: '0644'
  register: backports_source
  
- name: Update apt cache if backports file was just added
  become: true
  apt:
    update_cache: yes
  when: backports_source.changed

- name: Install kernel and AMD GPU firmware from backports
  become: true
  apt:
    name: 
      - linux-image-amd64
      - firmware-amd-graphics
    state: present
    default_release: trixie-backports
