- name: Enable Debian backports
  become: true
  copy:
    src: debian-backports.sources
    dest: /etc/apt/sources.list.d/debian-backports.sources
    owner: root
    group: root
    mode: '0644'
  register: backports_source

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install kernel and AMD GPU firmware from backports
  become: true
  apt:
    name: 
      - linux-image-amd64
      - firmware-amd-graphics
    state: latest
    default_release: trixie-backports
    update_cache: yes
