- name: Ensure mount point exists
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'

- name: Create systemd mount unit file
  template:
    src: mnt-myshare.mount.j2
    dest: "/etc/systemd/system/{{ unit_name }}"
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: true

- name: Enable systemd mount unit
  systemd:
    name: "{{ unit_name }}"
    daemon-reload: true
    enabled: true
    state: started
  become: true

- name: Ensure systemd mount unit is started
  systemd:
    name: "{{ unit_name }}"
    state: started
  become: true
