- name: Install wireguard
  become: true
  apt:
    name:
      - wireguard
      - resolvconf
    state: latest

- name: Create wireguard config
  become: true
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
