- name: Set GRUB_CMDLINE_LINUX_DEFAULT variable
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
    backrefs: yes
  register: grub_config

- name: Update GRUB configuration
  become: true
  command: update-grub
  when: grub_config.changed
