- name: Ensure git is installed
  become: true
  apt:
    name:
      - git
    state: latest

- name: Set global Git username
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: Set global Git email
  community.general.git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
