- name: Configure main workstation
  hosts: main_workstation
  roles:
    # - set-hostname
    # - apt-backports
    # - homelab-ca-certificate
    # - install-apt-packages
    # - install-flatpak-packages
    - generate-ssh-keys
