- name: Check if Tray Icons Reloaded is installed
  stat:
    path: ~/.local/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl
  register: extension_dir

- name: Install Tray Icons Reloaded
  command: gdbus call --session --dest org.gnome.Shell.Extensions --object-path /org/gnome/Shell/Extensions --method org.gnome.Shell.Extensions.InstallRemoteExtension "trayIconsReloaded@selfmade.pl"
  when: not extension_dir.stat.exists

# Extension settings
- name: Tray Icons Reloaded - Icon Size
  command: dconf write /org/gnome/shell/extensions/trayIconsReloaded/icon-size 16
  changed_when: false
- name: Tray Icons Reloaded - Tray Margin
  command: dconf write /org/gnome/shell/extensions/trayIconsReloaded/tray-margin-left 0
  changed_when: false
- name: Tray Icons Reloaded - Icon padding
  command: dconf write /org/gnome/shell/extensions/trayIconsReloaded/icon-padding-horizontal 4
  changed_when: false
